Rails_App/ZimbraPasswordReset/config/routes.rb
ZimbraPasswordReset::Application.routes.draw do
  devise_for :users
  resources :users
  match "/mailboxes/search", :controller => "mailboxes", :action => "search"
  match "/mailboxes/reset_password", :controller => "mailboxes", :action => "reset_password"
  resources :mailboxes, :constraints => { :id => /.*/ }
  resources :password_resets
  root :to => "mailboxes#index"
end

Rails_App/ZimbraPasswordReset/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Cambio Clave UCSC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <% if flash[:redirect] %>
	<meta HTTP-EQUIV="REFRESH" content="7; url=http://moises.ucsc.cl/">
  <% end %>
</head>
<body>

<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="<%= mailboxes_path()%>">
				<%= image_tag "http://www.ucsc.cl/wp-content/themes/ucsc/img/logo/ucsc-header.png"%>
			</a>
			<!-- <div style="margin-top: 20px;text-align: center;">
						<a class="brand" href="#">
							<h2>Administracion de Zimbra</h2>
						</a>
					</div> -->
			<div id="user-greet">
				<% if current_user %>
					<%= current_user.email %> |
					<%= link_to "Salir", destroy_user_session_path, :method => :delete %>
				<% end %>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid">
	<% flash.each do |name, msg| %>
		<% unless name == :redirect %>
		  <div class=" alert alert-<%= name == :notice ? "success" : "error" %>">
		    <a class="close" data-dismiss="alert">×</a>
		    <%= msg %>
		  </div>
		<% end %>
	<% end %>
    <div id="main" class="">
      <%= yield %>
    </div>
</div>


</body>
</html>